# Generated by Django 4.0 on 2021-12-14 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addToStorage', '0002_rename_equipmenttype_id_equipments_equipmenttype_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmenttype',
            name='serialNumberMask',
            field=models.CharField(max_length=100),
        ),
    ]
